#! /bin/sh
# /etc/init.d/stat_logger

### BEGIN INIT INFO
# Provides:          stat_logger 
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple service to log Rest API result 
# Description:       Statistic logger for a remote API
### END INIT INFO

case "$1" in
  start)
    echo "Starting stat_logger"
    /home/orbital/dev/pi/a.out
   ;;
  stop)
    if [ -f /tmp/stat_logger.pid ]; then
      echo "Stopping stat_logger"
      kill `cat /tmp/stat_logger.pid`
    else
      echo "Nothing to stop, consider starting the service first"
    fi
    ;;
  status)
    if [ -f /tmp/stat_logger.pid ]; then
      echo "stat_logger is running"
    else
      echo "stat_logger is not running"
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/stat_logger {start|stop|status}"
    exit 1
    ;;
esac

exit 0
