#!/bin/sh
# /etc/init.d/stat_logger

### BEGIN INIT INFO
# Provides:          stat_logger 
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple service to log Rest API result 
# Description:       Statistic logger for a remote API
### END INIT INFO

PID_FILE="/var/run/stat_logger.pid"
EXEC_FILE="/usr/local/bin/stat_logger"

case "$1" in
  start)
    echo "Starting stat_logger"
    $EXEC_FILE
    ;;
  stop)
    if [ -f $PID_FILE ]; then
      echo "Stopping stat_logger"
      kill `cat $PID_FILE`
      rm $PID_FILE
    else
      echo "Nothing to stop, consider starting the service first"
    fi
    ;;
  status)
    if [ -f $PID_FILE ]; then
      echo "stat_logger is running"
    else
      echo "stat_logger is not running"
    fi
    ;;
  *)
    echo "Usage: service stat_logger {start|stop|status}"
    exit 1
    ;;
esac

exit 0
